#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("iSeconds.Resource", IsApplication=true)]

namespace iSeconds
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
			iSeconds.Domain.Resource.String.library_name = iSeconds.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int calendarView2 = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int cancel_timeline_creation_button = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int createTimeline = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int create_timeline_button = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int image = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int layoutCalendar = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int mainLayout = 2131099653;
			
			// aapt resource value: 0x7f060010
			public const int menu_media_sandbox = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int menu_timelines = 2131099665;
			
			// aapt resource value: 0x7f060008
			public const int pickPhotoButton = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int pickVideoButton = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int surfacevideoview = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int takePhotoButton = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int takeVideoButton = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int timeline_name_edit = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int timeline_name_label = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int userTimelinesLayout = 2131099662;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateTimeline = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MediaSandbox = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Timeline = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int UserTimelines = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MenuItems = 2131034112;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int create_timeline = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int create_timeline_button = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int timeline_name = 2130968580;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
