#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.17929
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("iSeconds.Android.Application.Resource", IsApplication=true)]

namespace iSeconds.Android.Application
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
			iSeconds.Domain.Resource.String.library_name = iSeconds.Android.Application.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int createTimeline = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int create_timeline_button = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int image = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int pickPhotoButton = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int pickVideoButton = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int surfacevideoview = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int takePhotoButton = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int takeVideoButton = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int timeline_name_edit = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int timeline_name_label = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateTimeline = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int create_timeline = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int create_timeline_button = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int timeline_name = 2130968580;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
