#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18051
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("iSeconds.Droid.Resource", IsApplication=true)]

namespace iSeconds.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LegacyBar.Library.Resource.Attribute.background = global::iSeconds.Droid.Resource.Attribute.background;
			global::LegacyBar.Library.Resource.Attribute.background_item = global::iSeconds.Droid.Resource.Attribute.background_item;
			global::LegacyBar.Library.Resource.Attribute.separator = global::iSeconds.Droid.Resource.Attribute.separator;
			global::LegacyBar.Library.Resource.Attribute.title = global::iSeconds.Droid.Resource.Attribute.title;
			global::LegacyBar.Library.Resource.Attribute.title_color = global::iSeconds.Droid.Resource.Attribute.title_color;
			global::LegacyBar.Library.Resource.Color.Red = global::iSeconds.Droid.Resource.Color.Red;
			global::LegacyBar.Library.Resource.Color.actionbar_background_end = global::iSeconds.Droid.Resource.Color.actionbar_background_end;
			global::LegacyBar.Library.Resource.Color.actionbar_background_end_alt = global::iSeconds.Droid.Resource.Color.actionbar_background_end_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end = global::iSeconds.Droid.Resource.Color.actionbar_background_item_pressed_end;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end_alt = global::iSeconds.Droid.Resource.Color.actionbar_background_item_pressed_end_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start = global::iSeconds.Droid.Resource.Color.actionbar_background_item_pressed_start;
			global::LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start_alt = global::iSeconds.Droid.Resource.Color.actionbar_background_item_pressed_start_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_background_start = global::iSeconds.Droid.Resource.Color.actionbar_background_start;
			global::LegacyBar.Library.Resource.Color.actionbar_background_start_alt = global::iSeconds.Droid.Resource.Color.actionbar_background_start_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_separator = global::iSeconds.Droid.Resource.Color.actionbar_separator;
			global::LegacyBar.Library.Resource.Color.actionbar_separator_alt = global::iSeconds.Droid.Resource.Color.actionbar_separator_alt;
			global::LegacyBar.Library.Resource.Color.actionbar_title = global::iSeconds.Droid.Resource.Color.actionbar_title;
			global::LegacyBar.Library.Resource.Color.actionbar_title_alt = global::iSeconds.Droid.Resource.Color.actionbar_title_alt;
			global::LegacyBar.Library.Resource.Color.black = global::iSeconds.Droid.Resource.Color.black;
			global::LegacyBar.Library.Resource.Color.blue = global::iSeconds.Droid.Resource.Color.blue;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_end = global::iSeconds.Droid.Resource.Color.bottomactionbar_background_end;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_end = global::iSeconds.Droid.Resource.Color.bottomactionbar_background_item_pressed_end;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_start = global::iSeconds.Droid.Resource.Color.bottomactionbar_background_item_pressed_start;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_background_start = global::iSeconds.Droid.Resource.Color.bottomactionbar_background_start;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_separator = global::iSeconds.Droid.Resource.Color.bottomactionbar_separator;
			global::LegacyBar.Library.Resource.Color.bottomactionbar_title = global::iSeconds.Droid.Resource.Color.bottomactionbar_title;
			global::LegacyBar.Library.Resource.Color.green = global::iSeconds.Droid.Resource.Color.green;
			global::LegacyBar.Library.Resource.Color.grey = global::iSeconds.Droid.Resource.Color.grey;
			global::LegacyBar.Library.Resource.Color.red = global::iSeconds.Droid.Resource.Color.red;
			global::LegacyBar.Library.Resource.Color.white = global::iSeconds.Droid.Resource.Color.white;
			global::LegacyBar.Library.Resource.Color.yellow = global::iSeconds.Droid.Resource.Color.yellow;
			global::LegacyBar.Library.Resource.Dimension.actionbar_height = global::iSeconds.Droid.Resource.Dimension.actionbar_height;
			global::LegacyBar.Library.Resource.Dimension.actionbar_home_item_width = global::iSeconds.Droid.Resource.Dimension.actionbar_home_item_width;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height = global::iSeconds.Droid.Resource.Dimension.actionbar_item_height;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height_over = global::iSeconds.Droid.Resource.Dimension.actionbar_item_height_over;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_height_overflow = global::iSeconds.Droid.Resource.Dimension.actionbar_item_height_overflow;
			global::LegacyBar.Library.Resource.Dimension.actionbar_item_width = global::iSeconds.Droid.Resource.Dimension.actionbar_item_width;
			global::LegacyBar.Library.Resource.Drawable.actionbar_back_indicator = global::iSeconds.Droid.Resource.Drawable.actionbar_back_indicator;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background = global::iSeconds.Droid.Resource.Drawable.actionbar_background;
			global::LegacyBar.Library.Resource.Drawable.actionbar_background_alt = global::iSeconds.Droid.Resource.Drawable.actionbar_background_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn = global::iSeconds.Droid.Resource.Drawable.actionbar_btn;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_alt = global::iSeconds.Droid.Resource.Drawable.actionbar_btn_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_normal = global::iSeconds.Droid.Resource.Drawable.actionbar_btn_normal;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_normal_alt = global::iSeconds.Droid.Resource.Drawable.actionbar_btn_normal_alt;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed = global::iSeconds.Droid.Resource.Drawable.actionbar_btn_pressed;
			global::LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed_alt = global::iSeconds.Droid.Resource.Drawable.actionbar_btn_pressed_alt;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_background = global::iSeconds.Droid.Resource.Drawable.bottomactionbar_background;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn = global::iSeconds.Droid.Resource.Drawable.bottomactionbar_btn;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_normal = global::iSeconds.Droid.Resource.Drawable.bottomactionbar_btn_normal;
			global::LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_pressed = global::iSeconds.Droid.Resource.Drawable.bottomactionbar_btn_pressed;
			global::LegacyBar.Library.Resource.Drawable.ic_action_down = global::iSeconds.Droid.Resource.Drawable.ic_action_down;
			global::LegacyBar.Library.Resource.Drawable.ic_action_left = global::iSeconds.Droid.Resource.Drawable.ic_action_left;
			global::LegacyBar.Library.Resource.Drawable.ic_action_overflow_dark = global::iSeconds.Droid.Resource.Drawable.ic_action_overflow_dark;
			global::LegacyBar.Library.Resource.Drawable.ic_action_refresh_dark = global::iSeconds.Droid.Resource.Drawable.ic_action_refresh_dark;
			global::LegacyBar.Library.Resource.Drawable.ic_action_right = global::iSeconds.Droid.Resource.Drawable.ic_action_right;
			global::LegacyBar.Library.Resource.Drawable.ic_action_search_dark = global::iSeconds.Droid.Resource.Drawable.ic_action_search_dark;
			global::LegacyBar.Library.Resource.Drawable.ic_action_up = global::iSeconds.Droid.Resource.Drawable.ic_action_up;
			global::LegacyBar.Library.Resource.Drawable.ic_launcher = global::iSeconds.Droid.Resource.Drawable.ic_launcher;
			global::LegacyBar.Library.Resource.Drawable.ic_menu_down = global::iSeconds.Droid.Resource.Drawable.ic_menu_down;
			global::LegacyBar.Library.Resource.Drawable.ic_menu_left = global::iSeconds.Droid.Resource.Drawable.ic_menu_left;
			global::LegacyBar.Library.Resource.Drawable.ic_menu_refresh = global::iSeconds.Droid.Resource.Drawable.ic_menu_refresh;
			global::LegacyBar.Library.Resource.Drawable.ic_menu_right = global::iSeconds.Droid.Resource.Drawable.ic_menu_right;
			global::LegacyBar.Library.Resource.Drawable.ic_menu_search = global::iSeconds.Droid.Resource.Drawable.ic_menu_search;
			global::LegacyBar.Library.Resource.Drawable.ic_menu_up = global::iSeconds.Droid.Resource.Drawable.ic_menu_up;
			global::LegacyBar.Library.Resource.Drawable.ic_title_export_default = global::iSeconds.Droid.Resource.Drawable.ic_title_export_default;
			global::LegacyBar.Library.Resource.Drawable.ic_title_share_default = global::iSeconds.Droid.Resource.Drawable.ic_title_share_default;
			global::LegacyBar.Library.Resource.Id.actionbar_actions = global::iSeconds.Droid.Resource.Id.actionbar_actions;
			global::LegacyBar.Library.Resource.Id.actionbar_home = global::iSeconds.Droid.Resource.Id.actionbar_home;
			global::LegacyBar.Library.Resource.Id.actionbar_home_bg = global::iSeconds.Droid.Resource.Id.actionbar_home_bg;
			global::LegacyBar.Library.Resource.Id.actionbar_home_btn = global::iSeconds.Droid.Resource.Id.actionbar_home_btn;
			global::LegacyBar.Library.Resource.Id.actionbar_home_is_back = global::iSeconds.Droid.Resource.Id.actionbar_home_is_back;
			global::LegacyBar.Library.Resource.Id.actionbar_home_logo = global::iSeconds.Droid.Resource.Id.actionbar_home_logo;
			global::LegacyBar.Library.Resource.Id.actionbar_item = global::iSeconds.Droid.Resource.Id.actionbar_item;
			global::LegacyBar.Library.Resource.Id.actionbar_progress = global::iSeconds.Droid.Resource.Id.actionbar_progress;
			global::LegacyBar.Library.Resource.Id.actionbar_title = global::iSeconds.Droid.Resource.Id.actionbar_title;
			global::LegacyBar.Library.Resource.Id.actionbar_title_layout = global::iSeconds.Droid.Resource.Id.actionbar_title_layout;
			global::LegacyBar.Library.Resource.Id.overflow_spinner = global::iSeconds.Droid.Resource.Id.overflow_spinner;
			global::LegacyBar.Library.Resource.Id.screen = global::iSeconds.Droid.Resource.Id.screen;
			global::LegacyBar.Library.Resource.Layout.actionbar = global::iSeconds.Droid.Resource.Layout.actionbar;
			global::LegacyBar.Library.Resource.Layout.actionbar_item = global::iSeconds.Droid.Resource.Layout.actionbar_item;
			global::LegacyBar.Library.Resource.Layout.blankspinner = global::iSeconds.Droid.Resource.Layout.blankspinner;
			global::LegacyBar.Library.Resource.Layout.overflowactionbar_item = global::iSeconds.Droid.Resource.Layout.overflowactionbar_item;
			global::LegacyBar.Library.Resource.Layout.spinneritem = global::iSeconds.Droid.Resource.Layout.spinneritem;
			global::LegacyBar.Library.Resource.String.Hello = global::iSeconds.Droid.Resource.String.Hello;
			global::LegacyBar.Library.Resource.String.actionbar_activity_not_found = global::iSeconds.Droid.Resource.String.actionbar_activity_not_found;
			global::LegacyBar.Library.Resource.String.app_name = global::iSeconds.Droid.Resource.String.app_name;
			global::LegacyBar.Library.Resource.String.menu_string_down = global::iSeconds.Droid.Resource.String.menu_string_down;
			global::LegacyBar.Library.Resource.String.menu_string_left = global::iSeconds.Droid.Resource.String.menu_string_left;
			global::LegacyBar.Library.Resource.String.menu_string_refresh = global::iSeconds.Droid.Resource.String.menu_string_refresh;
			global::LegacyBar.Library.Resource.String.menu_string_right = global::iSeconds.Droid.Resource.String.menu_string_right;
			global::LegacyBar.Library.Resource.String.menu_string_search = global::iSeconds.Droid.Resource.String.menu_string_search;
			global::LegacyBar.Library.Resource.String.menu_string_up = global::iSeconds.Droid.Resource.String.menu_string_up;
			global::LegacyBar.Library.Resource.String.some_title = global::iSeconds.Droid.Resource.String.some_title;
			global::LegacyBar.Library.Resource.Style.MyTheme = global::iSeconds.Droid.Resource.Style.MyTheme;
			global::LegacyBar.Library.Resource.Style.actionbar = global::iSeconds.Droid.Resource.Style.actionbar;
			global::LegacyBar.Library.Resource.Style.actionbarhomeitem = global::iSeconds.Droid.Resource.Style.actionbarhomeitem;
			global::LegacyBar.Library.Resource.Style.actionbarhomelogo = global::iSeconds.Droid.Resource.Style.actionbarhomelogo;
			global::LegacyBar.Library.Resource.Style.actionbaritem = global::iSeconds.Droid.Resource.Style.actionbaritem;
			global::LegacyBar.Library.Resource.Style.actionbarprogressbar = global::iSeconds.Droid.Resource.Style.actionbarprogressbar;
			global::LegacyBar.Library.Resource.Style.clearbutton = global::iSeconds.Droid.Resource.Style.clearbutton;
			global::LegacyBar.Library.Resource.Styleable.actionbar = global::iSeconds.Droid.Resource.Styleable.actionbar;
			global::LegacyBar.Library.Resource.Styleable.actionbar_background = global::iSeconds.Droid.Resource.Styleable.actionbar_background;
			global::LegacyBar.Library.Resource.Styleable.actionbar_background_item = global::iSeconds.Droid.Resource.Styleable.actionbar_background_item;
			global::LegacyBar.Library.Resource.Styleable.actionbar_separator = global::iSeconds.Droid.Resource.Styleable.actionbar_separator;
			global::LegacyBar.Library.Resource.Styleable.actionbar_title = global::iSeconds.Droid.Resource.Styleable.actionbar_title;
			global::LegacyBar.Library.Resource.Styleable.actionbar_title_color = global::iSeconds.Droid.Resource.Styleable.actionbar_title_color;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int background = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int background_item = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int separator = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int title = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int title_color = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040019
			public const int Red = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int actionbar_background = 2130968602;
			
			// aapt resource value: 0x7f040003
			public const int actionbar_background_end = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int actionbar_background_end_alt = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int actionbar_background_item_pressed_end = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int actionbar_background_item_pressed_end_alt = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int actionbar_background_item_pressed_start = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int actionbar_background_item_pressed_start_alt = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int actionbar_background_start = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int actionbar_background_start_alt = 2130968584;
			
			// aapt resource value: 0x7f04001b
			public const int actionbar_pressedcolor = 2130968603;
			
			// aapt resource value: 0x7f040000
			public const int actionbar_separator = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int actionbar_separator_alt = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int actionbar_title = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int actionbar_title_alt = 2130968583;
			
			// aapt resource value: 0x7f04001f
			public const int activity_background = 2130968607;
			
			// aapt resource value: 0x7f040013
			public const int black = 2130968595;
			
			// aapt resource value: 0x7f040016
			public const int blue = 2130968598;
			
			// aapt resource value: 0x7f04000f
			public const int bottomactionbar_background_end = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int bottomactionbar_background_item_pressed_end = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int bottomactionbar_background_item_pressed_start = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public const int bottomactionbar_background_start = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int bottomactionbar_separator = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int bottomactionbar_title = 2130968589;
			
			// aapt resource value: 0x7f04001c
			public const int calendar_title_background = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int calendar_title_color = 2130968605;
			
			// aapt resource value: 0x7f040021
			public const int first_item_color = 2130968609;
			
			// aapt resource value: 0x7f040014
			public const int green = 2130968596;
			
			// aapt resource value: 0x7f040017
			public const int grey = 2130968599;
			
			// aapt resource value: 0x7f040020
			public const int list_divider_color = 2130968608;
			
			// aapt resource value: 0x7f040015
			public const int red = 2130968597;
			
			// aapt resource value: 0x7f040022
			public const int second_item_color = 2130968610;
			
			// aapt resource value: 0x7f04001e
			public const int secondary_activities_background = 2130968606;
			
			// aapt resource value: 0x7f040012
			public const int white = 2130968594;
			
			// aapt resource value: 0x7f040018
			public const int yellow = 2130968600;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int actionbar_height = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int actionbar_home_item_width = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_item_height = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int actionbar_item_height_over = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int actionbar_item_height_overflow = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int actionbar_item_width = 2131034115;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_background_alt = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_btn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_btn_alt = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int actionbar_btn_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int actionbar_btn_normal_alt = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int actionbar_btn_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int actionbar_btn_pressed_alt = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int actionbar_button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bottomactionbar_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bottomactionbar_btn = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bottomactionbar_btn_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bottomactionbar_btn_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int broditech_power = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int facebook = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_down = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_left = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_overflow_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_refresh_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_right = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_search_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_action_up = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_add = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_camera = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_check = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_day_videos = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_home = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_launcher = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_logo = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_menu = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_menu_down = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_menu_left = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_menu_refresh = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_menu_right = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_menu_search = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_menu_up = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_setting = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_settings = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_share = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_title_export_default = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_title_share_default = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_uncheck = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Icon = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int indicator_check_mark = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int splash_title = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int splash_title_land = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int twitter = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int actionbar = 2131296256;
			
			// aapt resource value: 0x7f090010
			public const int actionbar_actions = 2131296272;
			
			// aapt resource value: 0x7f09003d
			public const int actionbar_back_to_home = 2131296317;
			
			// aapt resource value: 0x7f09000b
			public const int actionbar_home = 2131296267;
			
			// aapt resource value: 0x7f09000d
			public const int actionbar_home_bg = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int actionbar_home_btn = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int actionbar_home_is_back = 2131296271;
			
			// aapt resource value: 0x7f09000c
			public const int actionbar_home_logo = 2131296268;
			
			// aapt resource value: 0x7f090014
			public const int actionbar_item = 2131296276;
			
			// aapt resource value: 0x7f090043
			public const int actionbar_more = 2131296323;
			
			// aapt resource value: 0x7f090012
			public const int actionbar_progress = 2131296274;
			
			// aapt resource value: 0x7f090040
			public const int actionbar_settings = 2131296320;
			
			// aapt resource value: 0x7f090041
			public const int actionbar_share = 2131296321;
			
			// aapt resource value: 0x7f090042
			public const int actionbar_takeVideo = 2131296322;
			
			// aapt resource value: 0x7f09003f
			public const int actionbar_timeline_add = 2131296319;
			
			// aapt resource value: 0x7f09003e
			public const int actionbar_timeline_menu_options = 2131296318;
			
			// aapt resource value: 0x7f090013
			public const int actionbar_title = 2131296275;
			
			// aapt resource value: 0x7f090011
			public const int actionbar_title_layout = 2131296273;
			
			// aapt resource value: 0x7f090015
			public const int calendarMonthName = 2131296277;
			
			// aapt resource value: 0x7f090017
			public const int calendarView = 2131296279;
			
			// aapt resource value: 0x7f090016
			public const int calendarWeekDays = 2131296278;
			
			// aapt resource value: 0x7f09002b
			public const int dateEndPeriod = 2131296299;
			
			// aapt resource value: 0x7f090029
			public const int dateStartPeriod = 2131296297;
			
			// aapt resource value: 0x7f090003
			public const int imageBroditech = 2131296259;
			
			// aapt resource value: 0x7f090008
			public const int imageFacebook = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int imageTwitter = 2131296265;
			
			// aapt resource value: 0x7f09002d
			public const int imageViewTitle = 2131296301;
			
			// aapt resource value: 0x7f090034
			public const int linearLayout = 2131296308;
			
			// aapt resource value: 0x7f090002
			public const int linearLayout1 = 2131296258;
			
			// aapt resource value: 0x7f090007
			public const int linearLayout2 = 2131296263;
			
			// aapt resource value: 0x7f090005
			public const int linearLayout3 = 2131296261;
			
			// aapt resource value: 0x7f090020
			public const int main_more_content_about = 2131296288;
			
			// aapt resource value: 0x7f09001f
			public const int main_more_content_settings = 2131296287;
			
			// aapt resource value: 0x7f09001e
			public const int main_more_content_share = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int main_more_content_timeline_options = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int overflow_spinner = 2131296284;
			
			// aapt resource value: 0x7f090039
			public const int progressBar1 = 2131296313;
			
			// aapt resource value: 0x7f09000a
			public const int screen = 2131296266;
			
			// aapt resource value: 0x7f090001
			public const int scrollView1 = 2131296257;
			
			// aapt resource value: 0x7f090027
			public const int settingWarning = 2131296295;
			
			// aapt resource value: 0x7f090022
			public const int settingsDescription = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int settingsTitle = 2131296289;
			
			// aapt resource value: 0x7f090023
			public const int settingsVideoSizeGroup = 2131296291;
			
			// aapt resource value: 0x7f090026
			public const int settingsVideoSizeLarge = 2131296294;
			
			// aapt resource value: 0x7f090025
			public const int settingsVideoSizeMedium = 2131296293;
			
			// aapt resource value: 0x7f090024
			public const int settingsVideoSizeSmall = 2131296292;
			
			// aapt resource value: 0x7f09002c
			public const int shareButton = 2131296300;
			
			// aapt resource value: 0x7f090036
			public const int surfaceView = 2131296310;
			
			// aapt resource value: 0x7f090004
			public const int textAbout = 2131296260;
			
			// aapt resource value: 0x7f090032
			public const int textDescription = 2131296306;
			
			// aapt resource value: 0x7f09002a
			public const int textEndPeriod = 2131296298;
			
			// aapt resource value: 0x7f090030
			public const int textName = 2131296304;
			
			// aapt resource value: 0x7f090006
			public const int textSite = 2131296262;
			
			// aapt resource value: 0x7f090028
			public const int textStartPeriod = 2131296296;
			
			// aapt resource value: 0x7f090038
			public const int textTotalProgress = 2131296312;
			
			// aapt resource value: 0x7f09002e
			public const int textViewBroditech = 2131296302;
			
			// aapt resource value: 0x7f090033
			public const int timelineDescription = 2131296307;
			
			// aapt resource value: 0x7f090031
			public const int timelineName = 2131296305;
			
			// aapt resource value: 0x7f090019
			public const int timelineOptionsMessage = 2131296281;
			
			// aapt resource value: 0x7f09002f
			public const int timelines = 2131296303;
			
			// aapt resource value: 0x7f09001b
			public const int videoItem = 2131296283;
			
			// aapt resource value: 0x7f090037
			public const int videoPlayerThumbnail = 2131296311;
			
			// aapt resource value: 0x7f09001a
			public const int videoThumbnail = 2131296282;
			
			// aapt resource value: 0x7f090035
			public const int videoThumbnails = 2131296309;
			
			// aapt resource value: 0x7f09003b
			public const int videoUploadName = 2131296315;
			
			// aapt resource value: 0x7f09003c
			public const int videoUploadProgress = 2131296316;
			
			// aapt resource value: 0x7f09003a
			public const int videoUploadThumbnail = 2131296314;
			
			// aapt resource value: 0x7f090018
			public const int videosList = 2131296280;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int actionbar_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int blankspinner = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CalendarMonthViewLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DayOptions = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DayOptionsItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int overflowactionbar_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int OverflowMenu = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SettingsView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ShareView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int spinneritem = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SplashScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int TimelineOptions = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int TimelineOptionsEditTimeline = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int TimelineOptionsItem = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int TimelineView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int VideoPlayer = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int VideoThumbnail = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int VideoUpload = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int VideoUploadItem = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060030
			public const int about = 2131099696;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_activity_not_found = 2131099650;
			
			// aapt resource value: 0x7f06000e
			public const int actionbar_dayoptions_text = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int actionbar_timelines_text = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int add_timeline = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int app_description = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060019
			public const int cancel = 2131099673;
			
			// aapt resource value: 0x7f06001e
			public const int day_options_title = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int day_options_video_description = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int item_options_message = 2131099680;
			
			// aapt resource value: 0x7f06000b
			public const int library_name = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int menu_string_down = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int menu_string_left = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int menu_string_refresh = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int menu_string_right = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int menu_string_search = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int menu_string_up = 2131099653;
			
			// aapt resource value: 0x7f06002f
			public const int more = 2131099695;
			
			// aapt resource value: 0x7f06001b
			public const int no = 2131099675;
			
			// aapt resource value: 0x7f060018
			public const int ok = 2131099672;
			
			// aapt resource value: 0x7f060021
			public const int settings = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int settings_movies_size_description = 2131099683;
			
			// aapt resource value: 0x7f060027
			public const int settings_movies_size_large = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int settings_movies_size_medium = 2131099686;
			
			// aapt resource value: 0x7f060025
			public const int settings_movies_size_small = 2131099685;
			
			// aapt resource value: 0x7f060022
			public const int settings_movies_size_title = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int settings_movies_size_warning = 2131099684;
			
			// aapt resource value: 0x7f060028
			public const int share = 2131099688;
			
			// aapt resource value: 0x7f06002b
			public const int share_button = 2131099691;
			
			// aapt resource value: 0x7f06002a
			public const int share_end_period = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int share_start_period = 2131099689;
			
			// aapt resource value: 0x7f060003
			public const int some_title = 2131099651;
			
			// aapt resource value: 0x7f06002c
			public const int takeVideo = 2131099692;
			
			// aapt resource value: 0x7f06000f
			public const int timeline_default = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int timeline_menu_options = 2131099665;
			
			// aapt resource value: 0x7f060017
			public const int timeline_options_dialog_add_timeline = 2131099671;
			
			// aapt resource value: 0x7f06001d
			public const int timeline_options_dialog_delete_alert = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int timeline_options_dialog_delete_ask = 2131099676;
			
			// aapt resource value: 0x7f060016
			public const int timeline_options_dialog_edit_timeline = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int timeline_options_dialog_new_timeline = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int timeline_options_dialog_textDescription = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int timeline_options_dialog_textName = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int timeline_options_message = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int timeline_options_title = 2131099664;
			
			// aapt resource value: 0x7f06002d
			public const int video_upload_progress = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int video_upload_total_progress = 2131099694;
			
			// aapt resource value: 0x7f06001a
			public const int yes = 2131099674;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070009
			public const int ActionBarDropdownItem = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int MenubarMenuButton = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int MyTheme = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int Theme_Splash = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int actionbar = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int actionbarhomeitem = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int actionbarhomelogo = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int actionbaritem = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int actionbarprogressbar = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int clearbutton = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] actionbar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 3
			public const int actionbar_background = 3;
			
			// aapt resource value: 4
			public const int actionbar_background_item = 4;
			
			// aapt resource value: 2
			public const int actionbar_separator = 2;
			
			// aapt resource value: 0
			public const int actionbar_title = 0;
			
			// aapt resource value: 1
			public const int actionbar_title_color = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
