#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18034
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("iSeconds.Droid.Resource", IsApplication=true)]

namespace iSeconds.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
			LegacyBar.Library.Resource.Attribute.background = iSeconds.Droid.Resource.Attribute.background;
			LegacyBar.Library.Resource.Attribute.background_item = iSeconds.Droid.Resource.Attribute.background_item;
			LegacyBar.Library.Resource.Attribute.separator = iSeconds.Droid.Resource.Attribute.separator;
			LegacyBar.Library.Resource.Attribute.title = iSeconds.Droid.Resource.Attribute.title;
			LegacyBar.Library.Resource.Attribute.title_color = iSeconds.Droid.Resource.Attribute.title_color;
			LegacyBar.Library.Resource.Color.Red = iSeconds.Droid.Resource.Color.Red;
			LegacyBar.Library.Resource.Color.actionbar_background_end = iSeconds.Droid.Resource.Color.actionbar_background_end;
			LegacyBar.Library.Resource.Color.actionbar_background_end_alt = iSeconds.Droid.Resource.Color.actionbar_background_end_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end = iSeconds.Droid.Resource.Color.actionbar_background_item_pressed_end;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_end_alt = iSeconds.Droid.Resource.Color.actionbar_background_item_pressed_end_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start = iSeconds.Droid.Resource.Color.actionbar_background_item_pressed_start;
			LegacyBar.Library.Resource.Color.actionbar_background_item_pressed_start_alt = iSeconds.Droid.Resource.Color.actionbar_background_item_pressed_start_alt;
			LegacyBar.Library.Resource.Color.actionbar_background_start = iSeconds.Droid.Resource.Color.actionbar_background_start;
			LegacyBar.Library.Resource.Color.actionbar_background_start_alt = iSeconds.Droid.Resource.Color.actionbar_background_start_alt;
			LegacyBar.Library.Resource.Color.actionbar_separator = iSeconds.Droid.Resource.Color.actionbar_separator;
			LegacyBar.Library.Resource.Color.actionbar_separator_alt = iSeconds.Droid.Resource.Color.actionbar_separator_alt;
			LegacyBar.Library.Resource.Color.actionbar_title = iSeconds.Droid.Resource.Color.actionbar_title;
			LegacyBar.Library.Resource.Color.actionbar_title_alt = iSeconds.Droid.Resource.Color.actionbar_title_alt;
			LegacyBar.Library.Resource.Color.black = iSeconds.Droid.Resource.Color.black;
			LegacyBar.Library.Resource.Color.blue = iSeconds.Droid.Resource.Color.blue;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_end = iSeconds.Droid.Resource.Color.bottomactionbar_background_end;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_end = iSeconds.Droid.Resource.Color.bottomactionbar_background_item_pressed_end;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_item_pressed_start = iSeconds.Droid.Resource.Color.bottomactionbar_background_item_pressed_start;
			LegacyBar.Library.Resource.Color.bottomactionbar_background_start = iSeconds.Droid.Resource.Color.bottomactionbar_background_start;
			LegacyBar.Library.Resource.Color.bottomactionbar_separator = iSeconds.Droid.Resource.Color.bottomactionbar_separator;
			LegacyBar.Library.Resource.Color.bottomactionbar_title = iSeconds.Droid.Resource.Color.bottomactionbar_title;
			LegacyBar.Library.Resource.Color.green = iSeconds.Droid.Resource.Color.green;
			LegacyBar.Library.Resource.Color.grey = iSeconds.Droid.Resource.Color.grey;
			LegacyBar.Library.Resource.Color.red = iSeconds.Droid.Resource.Color.red;
			LegacyBar.Library.Resource.Color.white = iSeconds.Droid.Resource.Color.white;
			LegacyBar.Library.Resource.Color.yellow = iSeconds.Droid.Resource.Color.yellow;
			LegacyBar.Library.Resource.Dimension.actionbar_height = iSeconds.Droid.Resource.Dimension.actionbar_height;
			LegacyBar.Library.Resource.Dimension.actionbar_home_item_width = iSeconds.Droid.Resource.Dimension.actionbar_home_item_width;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height = iSeconds.Droid.Resource.Dimension.actionbar_item_height;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height_over = iSeconds.Droid.Resource.Dimension.actionbar_item_height_over;
			LegacyBar.Library.Resource.Dimension.actionbar_item_height_overflow = iSeconds.Droid.Resource.Dimension.actionbar_item_height_overflow;
			LegacyBar.Library.Resource.Dimension.actionbar_item_width = iSeconds.Droid.Resource.Dimension.actionbar_item_width;
			LegacyBar.Library.Resource.Drawable.actionbar_back_indicator = iSeconds.Droid.Resource.Drawable.actionbar_back_indicator;
			LegacyBar.Library.Resource.Drawable.actionbar_background = iSeconds.Droid.Resource.Drawable.actionbar_background;
			LegacyBar.Library.Resource.Drawable.actionbar_background_alt = iSeconds.Droid.Resource.Drawable.actionbar_background_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_btn = iSeconds.Droid.Resource.Drawable.actionbar_btn;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_alt = iSeconds.Droid.Resource.Drawable.actionbar_btn_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_normal = iSeconds.Droid.Resource.Drawable.actionbar_btn_normal;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_normal_alt = iSeconds.Droid.Resource.Drawable.actionbar_btn_normal_alt;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed = iSeconds.Droid.Resource.Drawable.actionbar_btn_pressed;
			LegacyBar.Library.Resource.Drawable.actionbar_btn_pressed_alt = iSeconds.Droid.Resource.Drawable.actionbar_btn_pressed_alt;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_background = iSeconds.Droid.Resource.Drawable.bottomactionbar_background;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn = iSeconds.Droid.Resource.Drawable.bottomactionbar_btn;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_normal = iSeconds.Droid.Resource.Drawable.bottomactionbar_btn_normal;
			LegacyBar.Library.Resource.Drawable.bottomactionbar_btn_pressed = iSeconds.Droid.Resource.Drawable.bottomactionbar_btn_pressed;
			LegacyBar.Library.Resource.Drawable.ic_action_down = iSeconds.Droid.Resource.Drawable.ic_action_down;
			LegacyBar.Library.Resource.Drawable.ic_action_left = iSeconds.Droid.Resource.Drawable.ic_action_left;
			LegacyBar.Library.Resource.Drawable.ic_action_overflow_dark = iSeconds.Droid.Resource.Drawable.ic_action_overflow_dark;
			LegacyBar.Library.Resource.Drawable.ic_action_refresh_dark = iSeconds.Droid.Resource.Drawable.ic_action_refresh_dark;
			LegacyBar.Library.Resource.Drawable.ic_action_right = iSeconds.Droid.Resource.Drawable.ic_action_right;
			LegacyBar.Library.Resource.Drawable.ic_action_search_dark = iSeconds.Droid.Resource.Drawable.ic_action_search_dark;
			LegacyBar.Library.Resource.Drawable.ic_action_up = iSeconds.Droid.Resource.Drawable.ic_action_up;
			LegacyBar.Library.Resource.Drawable.ic_launcher = iSeconds.Droid.Resource.Drawable.ic_launcher;
			LegacyBar.Library.Resource.Drawable.ic_menu_down = iSeconds.Droid.Resource.Drawable.ic_menu_down;
			LegacyBar.Library.Resource.Drawable.ic_menu_left = iSeconds.Droid.Resource.Drawable.ic_menu_left;
			LegacyBar.Library.Resource.Drawable.ic_menu_refresh = iSeconds.Droid.Resource.Drawable.ic_menu_refresh;
			LegacyBar.Library.Resource.Drawable.ic_menu_right = iSeconds.Droid.Resource.Drawable.ic_menu_right;
			LegacyBar.Library.Resource.Drawable.ic_menu_search = iSeconds.Droid.Resource.Drawable.ic_menu_search;
			LegacyBar.Library.Resource.Drawable.ic_menu_up = iSeconds.Droid.Resource.Drawable.ic_menu_up;
			LegacyBar.Library.Resource.Drawable.ic_title_export_default = iSeconds.Droid.Resource.Drawable.ic_title_export_default;
			LegacyBar.Library.Resource.Drawable.ic_title_share_default = iSeconds.Droid.Resource.Drawable.ic_title_share_default;
			LegacyBar.Library.Resource.Id.actionbar_actions = iSeconds.Droid.Resource.Id.actionbar_actions;
			LegacyBar.Library.Resource.Id.actionbar_home = iSeconds.Droid.Resource.Id.actionbar_home;
			LegacyBar.Library.Resource.Id.actionbar_home_bg = iSeconds.Droid.Resource.Id.actionbar_home_bg;
			LegacyBar.Library.Resource.Id.actionbar_home_btn = iSeconds.Droid.Resource.Id.actionbar_home_btn;
			LegacyBar.Library.Resource.Id.actionbar_home_is_back = iSeconds.Droid.Resource.Id.actionbar_home_is_back;
			LegacyBar.Library.Resource.Id.actionbar_home_logo = iSeconds.Droid.Resource.Id.actionbar_home_logo;
			LegacyBar.Library.Resource.Id.actionbar_item = iSeconds.Droid.Resource.Id.actionbar_item;
			LegacyBar.Library.Resource.Id.actionbar_progress = iSeconds.Droid.Resource.Id.actionbar_progress;
			LegacyBar.Library.Resource.Id.actionbar_title = iSeconds.Droid.Resource.Id.actionbar_title;
			LegacyBar.Library.Resource.Id.actionbar_title_layout = iSeconds.Droid.Resource.Id.actionbar_title_layout;
			LegacyBar.Library.Resource.Id.overflow_spinner = iSeconds.Droid.Resource.Id.overflow_spinner;
			LegacyBar.Library.Resource.Id.screen = iSeconds.Droid.Resource.Id.screen;
			LegacyBar.Library.Resource.Layout.actionbar = iSeconds.Droid.Resource.Layout.actionbar;
			LegacyBar.Library.Resource.Layout.actionbar_item = iSeconds.Droid.Resource.Layout.actionbar_item;
			LegacyBar.Library.Resource.Layout.blankspinner = iSeconds.Droid.Resource.Layout.blankspinner;
			LegacyBar.Library.Resource.Layout.overflowactionbar_item = iSeconds.Droid.Resource.Layout.overflowactionbar_item;
			LegacyBar.Library.Resource.Layout.spinneritem = iSeconds.Droid.Resource.Layout.spinneritem;
			LegacyBar.Library.Resource.String.Hello = iSeconds.Droid.Resource.String.Hello;
			LegacyBar.Library.Resource.String.actionbar_activity_not_found = iSeconds.Droid.Resource.String.actionbar_activity_not_found;
			LegacyBar.Library.Resource.String.app_name = iSeconds.Droid.Resource.String.app_name;
			LegacyBar.Library.Resource.String.menu_string_down = iSeconds.Droid.Resource.String.menu_string_down;
			LegacyBar.Library.Resource.String.menu_string_left = iSeconds.Droid.Resource.String.menu_string_left;
			LegacyBar.Library.Resource.String.menu_string_refresh = iSeconds.Droid.Resource.String.menu_string_refresh;
			LegacyBar.Library.Resource.String.menu_string_right = iSeconds.Droid.Resource.String.menu_string_right;
			LegacyBar.Library.Resource.String.menu_string_search = iSeconds.Droid.Resource.String.menu_string_search;
			LegacyBar.Library.Resource.String.menu_string_up = iSeconds.Droid.Resource.String.menu_string_up;
			LegacyBar.Library.Resource.String.some_title = iSeconds.Droid.Resource.String.some_title;
			LegacyBar.Library.Resource.Style.MyTheme = iSeconds.Droid.Resource.Style.MyTheme;
			LegacyBar.Library.Resource.Style.actionbar = iSeconds.Droid.Resource.Style.actionbar;
			LegacyBar.Library.Resource.Style.actionbarhomeitem = iSeconds.Droid.Resource.Style.actionbarhomeitem;
			LegacyBar.Library.Resource.Style.actionbarhomelogo = iSeconds.Droid.Resource.Style.actionbarhomelogo;
			LegacyBar.Library.Resource.Style.actionbaritem = iSeconds.Droid.Resource.Style.actionbaritem;
			LegacyBar.Library.Resource.Style.actionbarprogressbar = iSeconds.Droid.Resource.Style.actionbarprogressbar;
			LegacyBar.Library.Resource.Style.clearbutton = iSeconds.Droid.Resource.Style.clearbutton;
			LegacyBar.Library.Resource.Styleable.actionbar = iSeconds.Droid.Resource.Styleable.actionbar;
			LegacyBar.Library.Resource.Styleable.actionbar_background = iSeconds.Droid.Resource.Styleable.actionbar_background;
			LegacyBar.Library.Resource.Styleable.actionbar_background_item = iSeconds.Droid.Resource.Styleable.actionbar_background_item;
			LegacyBar.Library.Resource.Styleable.actionbar_separator = iSeconds.Droid.Resource.Styleable.actionbar_separator;
			LegacyBar.Library.Resource.Styleable.actionbar_title = iSeconds.Droid.Resource.Styleable.actionbar_title;
			LegacyBar.Library.Resource.Styleable.actionbar_title_color = iSeconds.Droid.Resource.Styleable.actionbar_title_color;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int background = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int background_item = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int separator = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int title = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int title_color = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040019
			public const int Red = 2130968601;
			
			// aapt resource value: 0x7f040003
			public const int actionbar_background_end = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int actionbar_background_end_alt = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int actionbar_background_item_pressed_end = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int actionbar_background_item_pressed_end_alt = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int actionbar_background_item_pressed_start = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int actionbar_background_item_pressed_start_alt = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int actionbar_background_start = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int actionbar_background_start_alt = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int actionbar_separator = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int actionbar_separator_alt = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int actionbar_title = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int actionbar_title_alt = 2130968583;
			
			// aapt resource value: 0x7f040013
			public const int black = 2130968595;
			
			// aapt resource value: 0x7f040016
			public const int blue = 2130968598;
			
			// aapt resource value: 0x7f04000f
			public const int bottomactionbar_background_end = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int bottomactionbar_background_item_pressed_end = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int bottomactionbar_background_item_pressed_start = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public const int bottomactionbar_background_start = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int bottomactionbar_separator = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int bottomactionbar_title = 2130968589;
			
			// aapt resource value: 0x7f040014
			public const int green = 2130968596;
			
			// aapt resource value: 0x7f040017
			public const int grey = 2130968599;
			
			// aapt resource value: 0x7f040015
			public const int red = 2130968597;
			
			// aapt resource value: 0x7f040012
			public const int white = 2130968594;
			
			// aapt resource value: 0x7f040018
			public const int yellow = 2130968600;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int actionbar_height = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int actionbar_home_item_width = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_item_height = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int actionbar_item_height_over = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int actionbar_item_height_overflow = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int actionbar_item_width = 2131034115;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_background_alt = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_btn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_btn_alt = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int actionbar_btn_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int actionbar_btn_normal_alt = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int actionbar_btn_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int actionbar_btn_pressed_alt = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int actionbar_grayscale_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bottomactionbar_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bottomactionbar_btn = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bottomactionbar_btn_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bottomactionbar_btn_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_down = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_left = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_overflow_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_refresh_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_right = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_search_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_up = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_launcher = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_menu_down = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_menu_left = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_menu_refresh = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_menu_right = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_menu_search = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_menu_up = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_title_export_default = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_title_share_default = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int monthNameBackground = 2130837535;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080010
			public const int actionbar = 2131230736;
			
			// aapt resource value: 0x7f080006
			public const int actionbar_actions = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int actionbar_home = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int actionbar_home_bg = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int actionbar_home_btn = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int actionbar_home_is_back = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int actionbar_home_logo = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public const int actionbar_item = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int actionbar_progress = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int actionbar_title = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int actionbar_title_layout = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int calendarMonthName = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int calendarView = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int calendarWeekDays = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int homeViewLayout = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int myButton = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int overflow_spinner = 2131230738;
			
			// aapt resource value: 0x7f080000
			public const int screen = 2131230720;
			
			// aapt resource value: 0x7f080013
			public const int videoItemRadio = 2131230739;
			
			// aapt resource value: 0x7f08000e
			public const int videosList = 2131230734;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int blankspinner = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CalendarMonthViewLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DayOptions = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int HomeView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int overflowactionbar_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int spinneritem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int VideoItem = 2130903049;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_activity_not_found = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int hello = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int library_name = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int menu_string_down = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int menu_string_left = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int menu_string_refresh = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int menu_string_right = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int menu_string_search = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int menu_string_up = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int some_title = 2131099651;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070006
			public const int MyTheme = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int actionbar = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int actionbarhomeitem = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int actionbarhomelogo = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int actionbaritem = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int actionbarprogressbar = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int clearbutton = 2131165186;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] actionbar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 3
			public const int actionbar_background = 3;
			
			// aapt resource value: 4
			public const int actionbar_background_item = 4;
			
			// aapt resource value: 2
			public const int actionbar_separator = 2;
			
			// aapt resource value: 0
			public const int actionbar_title = 0;
			
			// aapt resource value: 1
			public const int actionbar_title_color = 1;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
