#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Yester_Camcorder.Resource", IsApplication=true)]

namespace Yester_Camcorder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_change_camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_record_media = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int camcorder1sec = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int camcorder3sec = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int camcorder5sec = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int camcorderCancelButton = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int camcorderCountdown = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int camcorderGroupTime = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int camcorderLayoutConfigRecord = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int camcorderLayoutRecord = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int camcorderLayoutResolution = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int camcorderPreviewCancelButton = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int camcorderPreviewConfirmButton = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int camcorderPreviewRetakeButton = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int camcorderPreviewVideo = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int camcorderRecordButton = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int camcorderResolution = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int camcorderSwapCamera = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int layoutCamcorder = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Camcorder = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CamcorderPreview = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int openCamera = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
